### ISSUE TITLE
Filtering By Properties w/ Invalid Characters in the Name

### ISSUE THREAD

**Issue by simonwarchol** [aplbrain/dotmotif#111]
Hey There,
I'm using dotmotif to query the neuPrint dataset and have found some of the neurons have properties that aren't accepted in the query string format
e.g. `'AVLP(R)': True,`

Is there a way to still query w/ these params?
I tried adding directly to the `_node_constraints`  but that doesn't seem to work either e.g.
```
motif._node_constraints['A']['AVLP(R)'] = {}
motif._node_constraints['A']['AVLP(R)']['='] = [True]

Variable `R` not defined (line 2, column 83 (offset: 156))
"    WHERE B.status = "Traced" AND A.status = "Orphan" AND A.INP = True AND A.AVLP(R) = True"
```

**Comment by j6k4m8** [comment]
Hi @simonwarchol — thank you so much for reporting this! I will work on a fix for this ASAP.

Would it be acceptable to use 'index-bracket' style notation?

```c
A -> B
A['AVLP(R)'] = true
```

Open to other suggestions!

**Comment by simonwarchol** [comment]
Hey @j6k4m8,
Yep -- that's the first thing I tried, so it's probably the most intuitive way to do it.
Really appreciate it! The framework is really impressive :) 
-Simon

**Comment by j6k4m8** [comment]
@simonwarchol I just pushed a new update (`dotmotif==0.11.0`) to PyPI and it should be installable with:

```shell
pip3 install -U dotmotif
```

Let me know if you're able to use the bracket syntax to execute your commands successfully now?

An example of the syntax in use is [here](https://github.com/aplbrain/dotmotif/blob/master/docs/examples/Searching%20in%20neuPrint.py)!

**Comment by simonwarchol** [comment]
Rad -- really appreciate it. Will test in the morning.
-Simon

**Comment by simonwarchol** [comment]
Looks great. Ty again

**Comment by j6k4m8** [comment]
Super awesome! Excited to see what you discover :)

**Comment by j6k4m8** [comment]
Super awesome — excited to hear how it goes!
