### ISSUE TITLE
Module Not Foud

### ISSUE THREAD

**Issue by anonimoustt** [aplbrain/dotmotif#137]
Hi,

I am getting following error while executing the following code:

from dotmotif import Motif
from dotmotif.executors.NeuPrintExecutor import NeuPrintExecutor

ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-5-3de76b8c472a>](https://localhost:8080/#) in <cell line: 2>()
      1 from dotmotif import Motif
----> 2 from dotmotif.executors.NeuPrintExecutor import NeuPrintExecutor

[/usr/local/lib/python3.10/dist-packages/dotmotif/executors/NeuPrintExecutor.py](https://localhost:8080/#) in <module>
      1 import pandas as pd
----> 2 from neuprint import Client
      3 from neuprint import fetch_all_rois
      4 
      5 from .. import Motif

ModuleNotFoundError: No module named 'neuprint'

**Comment by j6k4m8** [comment]
It looks like your installation doesn't have the `neuprint` library installed; you can either install it manually from the command-line with 

```bash
pip install neuprint-python
```

or you can re-install dotmotif with neuprint compatibility built-in, with 

```bash
pip install 'dotmotif[neuprint-python]'
```

**Comment by anonimoustt** [comment]
Hi,
Thanks. I needed to install additionally : 
!pip install py2neo
!pip install tamarind

to remove the error.

**Comment by j6k4m8** [comment]
Fantastic, thanks for reporting back! I will add these to the installation dependencies!!
