### ISSUE TITLE
RFC: Removing Neo4j / docker dependency from this library?

### ISSUE THREAD

**Issue by j6k4m8** [aplbrain/dotmotif#139]
Reaching out to a few known stakeholders to see if the community leverages the Neo4j / docker components of this library. We will keep the Cypher conversion, but looking for comments on if we could reasonably remove the provisioning aspect (with Tamarind). 

**Do you use DotMotif to create a local Docker container?**

cc @jakobtroidl @simonwarchol and some others at @aplbrain...

**Comment by jakobtroidl** [comment]
I personally have not used DotMotif to create a local Docker container and I think non of our lab members do so.

**Comment by j6k4m8** [comment]
Cool, thanks for the quick response @jakobtroidl!

**Comment by j6k4m8** [comment]
Also pinging @KeremKurban — I know you were looking at some larger graphs...

**Comment by KeremKurban** [comment]
same for me. i havent used it.

**Comment by j6k4m8** [comment]
Awesome thank you @KeremKurban! 

Based on this feedback and some email feedback I'm going to pull the docker provisioning code into its own python package (and OUT of this one). That should have the effect of improving installation quality-of-life and dependency management.

For those encountering this issue in the future, you can regain this capability by installing `dotmotif==0.13.0`.
